# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [109]:
%pip install mdutils

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.1 -> 26.2
[notice] To update, run: C:\Users\Pranav Wadatkar\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip


In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [111]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [112]:
print(np.__version__)

2.5.1


#### 3. Create a null vector of size 10 (★☆☆)

In [113]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [114]:
arr = np.eye(5)
print(np.size(arr)* arr.itemsize)


200


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [115]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [116]:
arr = np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [117]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [118]:
arr = np.arange(1,11)
print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [119]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [120]:
arr = np.array([1,2,0,0,4,0])
for i in range(arr.size):
    if arr[i]!=0:
        print(i)

print(np.nonzero(arr))

0
1
4
(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [121]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [122]:
print(np.random.random((3,3,3)))
hint(12)

[[[0.94697213 0.00465404 0.4201972 ]
  [0.11544336 0.68178796 0.3085125 ]
  [0.68860974 0.67255746 0.19856668]]

 [[0.26034744 0.09390635 0.62689704]
  [0.44322185 0.08892677 0.85478924]
  [0.49168862 0.30136999 0.41315824]]

 [[0.36534717 0.97569724 0.14364986]
  [0.22281362 0.6250655  0.8870029 ]
  [0.17750962 0.63668964 0.89874037]]]
hint: np.random.random


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [123]:
arr = np.random.randint(1,100,(10,10))
print(arr.max())
print(arr.min())

99
3


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [124]:
arr = np.random.random(30)
print(arr)
print(arr.mean())

[0.09622654 0.20835558 0.121754   0.88499578 0.19035984 0.23932202
 0.88751298 0.4985515  0.20146287 0.28799571 0.62909998 0.25989971
 0.95174249 0.26878237 0.02190132 0.87200243 0.61805211 0.61541981
 0.84922632 0.61972557 0.42703874 0.48058043 0.66211561 0.30018812
 0.66222742 0.73805852 0.25655729 0.46650645 0.7540812  0.84857474]
0.49727724786645694


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [125]:
# arr = np.eye(2)
# with np.nditer(arr,op_flags=["readwrite"]) as it:
#     for i in it:
#         if i == 0:
#             i[...] = 1
#         else:
#             i[...] = 0
# print(arr)  wrong 

answer(15)
Z = np.ones((7,7))
Z[1:-1,1:-1] = 0
print(Z)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [126]:
arr = np.random.randint(1,10,(3,3))
print(np.pad(arr,pad_width=1, mode="constant",constant_values=0))
print(arr)
answer(16)

[[0 0 0 0 0]
 [0 7 9 2 0]
 [0 2 4 5 0]
 [0 1 6 2 0]
 [0 0 0 0 0]]
[[7 9 2]
 [2 4 5]
 [1 6 2]]
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Not a solution to this problem but good to know: using fancy indexing for in-place edit
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [127]:
print(0.3 == 3 * 0.1)

False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [128]:
answer(18)
print(np.diag(np.arange(1,5),k=-1))

Z = np.diag(1+np.arange(4),k=-1)
print(Z)
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [129]:
# arr = np.arange(65)
# with np.nditer(arr, op_flags=["readwrite"]) as it:
#     for i in range(65):
#         if i%2==0:
#             it[i]=0
#         else:
#             it[i]=1
# print(arr)

arr = np.zeros((8,8))
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [130]:
arr = np.arange(1,337).reshape(6,7,8)
np.unravel_index(100,(6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [131]:
arr = np.array([[0,1],
                [1,0]])

print(np.tile(arr,(4,4)))

answer(21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [132]:
arr = np.random.random((5,5))
normed = (arr - arr.mean())/ arr.std()
print(normed)

answer(22)

[[-1.02147291  1.05294739 -1.24652748  0.63725274  0.64011283]
 [-0.59226418 -1.01588348 -1.52082015 -0.6083751   1.28440638]
 [ 0.90375406 -0.442274   -1.27975701 -0.91580572 -1.16152672]
 [ 0.60595753 -0.94792521  1.50542671  0.31655231 -0.16943175]
 [ 1.21878894  1.52167292 -0.34231568  1.53083518  0.0466724 ]]
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [133]:
answer(23)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [139]:
a5_3 = np.random.randint(1,100,(5,3))
a3_2 = np.random.randint(1,100,(3,2))
print(np.matmul(a5_3,a3_2))

[[6260 4536]
 [6576 4821]
 [8199 6907]
 [5485 4089]
 [8579 6907]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
# import numpy.ma as ma
# arr = np.random.randint(1,10,(25))
# print(ma.masked_inside(arr,3,8))
answer(25)
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[-- 2 -- 9 -- -- -- -- -- -- -- -- -- 1 -- -- -- -- -- -- -- 1 1 9 --]
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [147]:
print(sum(range(5),-1))

9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [153]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\Pranav Wadatkar\AppData\Local\Temp\ipykernel_16364\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [158]:
arr = np.array([-3.2,-3.1,-2.8,-2.3,-2.1,-1.5,-0.4,0,1.5,2.1,3.6,3.9])
result = np.sign(arr) * (np.ceil(np.abs(arr)))
print(arr)
print(result)
answer(29)

[-3.2 -3.1 -2.8 -2.3 -2.1 -1.5 -0.4  0.   1.5  2.1  3.6  3.9]
[-4. -4. -3. -3. -3. -2. -1.  0.  2.  3.  4.  4.]
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
print(np.intersect1d(arr,result))

[0.]
hint: np.intersect1d


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [166]:
np.seterr(all="ignore")

with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [169]:
print(np.emath.sqrt(-1)==np.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [178]:
today = np.datetime64('today','D')
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')
print(f"{yesterday}\n{today}\n{tomorrow}")

2026-08-05
2026-08-06
2026-08-07


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [187]:
dates = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [191]:
A = np.array([10,20,30], dtype=float)
B = np.array([40,50,60], dtype=float)

np.add(A,B,out=B)
np.divide(A,-2,out=A)
np.multiply(B,A,out=A)
print(A)

[ -250.  -700. -1350.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [200]:
print(np.tile(np.arange(5),(1,5)).reshape(5,5))

answer(37)
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [205]:
print(np.fromiter(range(10), dtype=float))

answer(38)
print(np.fromiter(range(10), dtype=float, count=-1))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [214]:
print(np.linspace(0.1,0.99,10))
answer(39)
print(np.linspace(0,1,11,endpoint=False)[1:])

[0.1        0.19888889 0.29777778 0.39666667 0.49555556 0.59444444
 0.69333333 0.79222222 0.89111111 0.99      ]
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [225]:
a = np.random.randint(1,1000,10)
print(np.sort(a))

answer(40)

[224 266 376 469 527 571 754 873 907 972]
Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [228]:
np.add.reduce(a)

np.int64(5939)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [233]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(np.allclose(a,b))
print(np.array_equal(a,b))

True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
a = np.array(["Can't edit"]).flags.writeable = False
a.flags.writeable = False

answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [263]:
arr = np.random.randint(1.0,10.0,(10,2))

X = arr[:,0]
Y = arr[:,1]

R = np.sqrt(X**2 + Y**2)
Theta = np.arctan2(Y,X)

print(arr)

print("Polar Coordinates")
print(R)
# PC = np.array([[R,Theta]]).flatten().reshape(10,2)
# print(PC)
print(Theta)

[[9 1]
 [8 5]
 [1 1]
 [1 1]
 [4 2]
 [7 5]
 [4 9]
 [3 8]
 [9 3]
 [1 7]]
Polar Coordinates
[9.05538514 9.43398113 1.41421356 1.41421356 4.47213595 8.60232527
 9.8488578  8.54400375 9.48683298 7.07106781]
[0.11065722 0.55859932 0.78539816 0.78539816 0.46364761 0.62024949
 1.152572   1.21202566 0.32175055 1.42889927]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [246]:
a=np.arange(0,10)
b,a[b]=a.max(),0
#a[b]=0
print(a)

answer(45)
a[a.argmax()]=0
print(a)

[0 1 2 3 4 5 6 7 8 0]
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)
[0 1 2 3 4 5 6 7 0 0]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [6]:
hint(46)

z = np.zeros((10,10),dtype=[("x",float),("y",float)])

x = np.linspace(0,1,10)
y = np.linspace(0,1,10)

x, y = np.meshgrid(x,y)
z["x"]=x
z["y"]=y
print(z[1,0])

hint: np.meshgrid
(0.0, 0.1111111111111111)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)