In [ ]:
%pip install numpy

In [ ]:
import numpy as np

list1= [1,2,3,4]
arr1 = np.array(list1)
print(type(arr1))
arr2d = np.array([list1,list1])
print(arr2d,arr2d.ndim)
arr2d = np.array([[list1,list1,list1]])
print(arr2d,arr2d.ndim)

In [ ]:
#basic functionc in numpy 
arr1 = np.array([[[1,2,3,4],[5,6,7,8],[1, 2, 3, 4]]])
print(arr1)
print("n_dim",arr1.ndim)
print("shape",arr1.shape)
print("size",arr1.size)
print("dtype",arr1.dtype)

In [ ]:
# array initialization
# zero array
zer0_arr = np.zeros((1,2,3))
print("Zero array\n",zer0_arr)

# one array
one_arr = np.ones((3,2))
print("one array\n",one_arr)

# Full array
full_arr = np.full((1,2,3),15)
print("Full array\n",full_arr)

In [ ]:
# identity matrix
id_arr = np.eye(3)
print("Identity matrix\n",id_arr)

In [ ]:
print(np.empty((4,2)))

print(np.arange(0,21,3))

print(np.linspace(0,20,6))

print(np.random.rand(2,3))

print(np.random.randint(1,100,(3,3)))

In [ ]:
# array indexing and slicing

a = np.arange(1,10,2)
print(a)
#slicing
print(a[0:3:1])

[1 3 5 7 9]


In [ ]:
two_D = np.array([[1,2,3],[4,5,6]])
print(two_D[0][1])

2


In [60]:
print(two_D[1])
print(two_D[1:])

[4 5 6]
[[4 5 6]]
